### ISSUE TITLE
[IMPROVEMENT] Make parent theme path configurable

### ISSUE THREAD

**Issue by shochdoerfer** [magesuite/frontend-builder#6]
When creating a new theme I would like to keep it in our own namespace and not in the creativestyle vendor namespace. I would love to see an option to point my theme to a parent theme folder, regardless of where it is located.

**Comment by drabikowy** [comment]
Fixed with
https://github.com/magesuite/frontend-builder/commit/867c21c21470318e1a5a0db156864276b8102753
thx to @marcoveeneman
