### ISSUE TITLE
Support OpenType fonts

### ISSUE THREAD

**Issue by marcoveeneman** [magesuite/frontend-builder#8]
Hi,

When trying to use an OpenType font as self hosted font, the frontend builder doesn't seem top copy the required `.otf` files.

Looking at the source code only the following formats seem to be supported: https://github.com/magesuite/frontend-builder/blob/9db62c2b0228a31acba0fa1f56c55d5922ba3e83/gulp/config/copyUnchanged.js#L11

So unfortunately no *.otf files are included. Was this left out on purpose or did no one need it yet? Could this file type be added?

If needed i can provide a PR.

**Comment by drabikowy** [comment]
Thank you for the hint. 
I've released frontend builder v4 (major only due to sass compiler change for newer node support) 
It contains the change you suggested.
Feel free to check it. 

https://gitlab.creativestyle.pl/m2c/magesuite-frontend-builder/-/blob/4.x/CHANGELOG.md
